### ISSUE TITLE
Add simh image file support to tape device

### ISSUE THREAD

**Issue by uweseimet** [uweseimet/scsi2pi#100]
This is a follow-up ticket to https://github.com/uweseimet/scsi2pi/issues/93. The tape device (SCPT) support in SCSI2Pi 4.0 focuses on reading and writing tar files. This has been tested with tar (Linux) and with Gemar (Atari).

In order to support more sophisticated tape drivers, which for instance make use of filemarks and of (reverse) spacing, a different image file format is required. tar files only contain the actual archived data, but not any other objects like filemarks or end-of-data markers, which are used by some drivers, e.g. bacula.

In the ideal case SCSI2Pi can use the same format that is used by open-simh, see https://github.com/open-simh/simh. See http://simh.trailing-edge.com/docs/simh_magtape.pdf for the specification of this file format.

**Comment by uweseimet** [comment]
@pacjunk The issue_100 branch now contains code that for .tap files supports the simh file format. I have already tested this code with my limited setup. tar can successfully write/read to/from .tap files in the new format. I downloaded http://www.bitsavers.org/bits/DEC/vax/vms/TK50/aq-mi45a-be_vms_v4_v5_mand_upd_1988.tap in order to see what happens when I use this image file together with tar. Of course this cannot work, but it reveals that at least the size of the first type object (a label I guess) is correctly evaluated:
```
[2024-11-11 22:28:12.431] [debug] (ID 3) - Controller is executing READ(6)/GET MESSAGE(6), CDB 08:01:00:00:14:00
[2024-11-11 22:28:12.431] [debug] (ID:LUN 3:0) - Device is executing READ(6)/GET MESSAGE(6) ($08)
[2024-11-11 22:28:12.431] [trace] (ID:LUN 3:0) - Position: 0, byte count: 10240
[2024-11-11 22:28:12.431] [trace] (ID:LUN 3:0) - Read simh header with class number 0, marker value/record length 80
[2024-11-11 22:28:12.431] [trace] (ID:LUN 3:0) - Searching for object type 0, found type 0 at position 0
[2024-11-11 22:28:12.431] [trace] (ID:LUN 3:0) - Actual block length of 80 byte(s) does not match expected block length of 512 byte(s)
[2024-11-11 22:28:12.432] [debug] (ID 3) - MEDIUM ERROR (Sense Key $03), NO ADDITIONAL_SENSE INFORMATION (ASC $00), ASCQ $00
```
When you start testing (e.g. by labelling a blank "tape") I expect some issues, new ones or known ones, we will see ...

**Comment by Pacjunk** [comment]
Wow, you have been busy overnight!  I'll see if I can make some time...

**Comment by Pacjunk** [comment]
OK, I rebuilt on the issue_100 branch and did some more testing (sorry still haven't connected that tape drive yet)...

I initialised (labelled) a tape (success)
[init.txt](https://github.com/user-attachments/files/17714055/init.txt)

then I mounted that tape using the label (success)
[mount.txt](https://github.com/user-attachments/files/17714072/mount.txt)

then I did a "dir" on the blank tape (success)
[dir empty.txt](https://github.com/user-attachments/files/17714076/dir.empty.txt)

then I attempted to copy a file to the tape (failed parity errors, device errors)
[copy file.txt](https://github.com/user-attachments/files/17714086/copy.file.txt)

Another "dir" on the tape (more parity errors etc)
[dir after copy.txt](https://github.com/user-attachments/files/17714094/dir.after.copy.txt)

I then connected a pre-existing simh image from bitsavers. I mounted the tape (success!)
[mount simh.txt](https://github.com/user-attachments/files/17714122/mount.simh.txt)

Then a "dir" on the tape to check contents (parity errors, but did display the first file name on the tape - not all)
[dir simh.txt](https://github.com/user-attachments/files/17714138/dir.simh.txt)


That is all I had time for tonight. I'll try to get to the physical tape drive soon...

**Comment by uweseimet** [comment]
@Pacjunk I'm afraid I don't know what a parity error in this context means. The tape code does not deal with parity. My guess is that your driver is not satisfied with the data it sees or there are (still) issues with the tape-related data returned by REQUEST SENSE.
I just fixed some code issues, please use the current issue_100 branch for your next test. Reminder: Always add information on the commit ID you were testing.
Please also do not forget to verify your web UI issue (see my comment in the issue_93 ticket about the web UI).

Regarding init.txt there is no command writing the label. Line 105 appears to successfully read it, so it must have been created before. Please ensure that no write operations are missing in the logs.

**Comment by Pacjunk** [comment]
Looks like my previous logs were truncated...

I ran some more test with build 99272d6.

Initialise a tape: [init2.txt](https://github.com/user-attachments/files/17740510/init2.txt)
Initialise a tape with erase: [init erase.txt](https://github.com/user-attachments/files/17740516/init.erase.txt)
Mount (any label) : [mount specified.txt](https://github.com/user-attachments/files/17740527/mount.specified.txt)
Mount (specified label) : [mount specified.txt](https://github.com/user-attachments/files/17740533/mount.specified.txt)
Copy File (still fails) : [copy file.txt](https://github.com/user-attachments/files/17740538/copy.file.txt)

According to the help, "parity error" could mean almost anything...
```
 		If this message is associated with a status code returned
                by a request to a magnetic tape driver, one or more of the
                following conditions can cause this error:

                  Attempt to read beyond the logical end of volume
                  Control bus parity error
                  Correctable data error (PE only)
                  Correctable skew (PE only)
                  CRC error (NRZI only)
                  Data bus parity error
                  Format error (PE only)
                  Invalid tape mark (NRZI only)
                  Longitudinal parity error (NRZI only)
                  Map parity error
                  MASSBUS control parity error
                  MASSBUS data parity error
                  Nonstandard gap
                  Read data substitute
                  Uncorrectable error (PE only)
                  Vertical parity error (NRZI only)


```

How do I do a debug build? I just do "make s2p". I assume there is some switch?

**Comment by uweseimet** [comment]
@Pacjunk Please refer to https://github.com/uweseimet/scsi2pi/wiki/Compilation-Instructions for build instructions.
https://github.com/uweseimet/scsi2pi/commit/99272d61fc62a167166c1f90d0fc726e14649769 is rather old. Please always used the latest available issue_100 branch for new tests. Otherwise you are spending time on outdated code.

**Comment by Pacjunk** [comment]
I'm sorry, but given that it takes 3-4 hours to do a build, I'm not constantly checking for updates. I tend to do a rebuild at night and then maybe test the next day. Because of time zone differences, this is when you make your changes so I'm always testing stale code. I will try the debug build. Also you edit your comments and github doesn't send an email for edits, only the original.

I managed to get a couple of tape drives working (had to reinstall in another enclosure), then one drive decided to chew some tapes, so this required dismantling to get the tapes out...

Anyway, these are the logs: (I tested first without a tape loaded, then with a tape loaded)

Sony SDT-5000 : 
[sdt5000.txt](https://github.com/user-attachments/files/17742423/sdt5000.txt)

DEC TZ87 in TK50/70 compatibility mode (read only): 
[tz87.txt](https://github.com/user-attachments/files/17742427/tz87.txt)

DEC TZ87 with TK85 tape:
[tz87_CT3.txt](https://github.com/user-attachments/files/17742439/tz87_CT3.txt)

I had some problems with that last drive. Not able to initialise tapes for some reason, but seems to read the tape and make all the right noises.

**Comment by Pacjunk** [comment]
OK, I rebuilt with debug to version 4e1f05a, and tested with the prebuilt simh image.

Mounting the tape (successfull):  
[mount.txt](https://github.com/user-attachments/files/17743954/mount.txt)

Directory listing of tape (failed):
[dir.txt](https://github.com/user-attachments/files/17743961/dir.txt)

Interestingly, this time I didn't get the generic parity error. The OS reported "file or directory lookup failed. magnetic tape position lost"

Is there some sort of utility/option that can "sniff" the traffic going to and from the real drive. Might be interesting to compare it to the emulated drive.

**Comment by Pacjunk** [comment]
Here is the dump of the file I'm using. It appears to *not* be in ANSI format. There are 4 files on the tape. VMS054.A,  .B, .C,  .D. Only the first filename (VMS054.A) is displayed before the error. The filenames are stored next to the data, so you need to wind through the tape to find them. 
[simh dump.txt](https://github.com/user-attachments/files/17744688/simh.dump.txt)

**Comment by uweseimet** [comment]
@Pacjunk I have had a quick look at the latest s2p logs, thank you. I don't think the mount log is required anymore, unless something changes for the worse and mounting fails. In dir.txt I stumble on this:
```
[2024-11-14 16:47:57.536] [debug] (ID 3) - Controller is executing SPACE(6), CDB 11:00:00:7f:ff:00
[2024-11-14 16:47:57.537] [debug] (ID:LUN 3:0) - Device is executing SPACE(6) ($11)
[2024-11-14 16:47:57.538] [trace] (ID:LUN 3:0) - Read SIMH header with class 0, value $0002000 at position 268
[2024-11-14 16:47:57.538] [trace] (ID:LUN 3:0) - Searching for object type 0, found type 0 at position 268
[2024-11-14 16:47:57.539] [trace] (ID:LUN 3:0) - Read SIMH header with class 0, value $4000100 at position 272
[2024-11-14 16:47:57.539] [trace] (ID:LUN 3:0) - Searching for object type 0, found type 0 at position 272
[2024-11-14 16:47:57.540] [trace] (ID:LUN 3:0) - Read SIMH header with class 0, value $0010001 at position 276
[2024-11-14 16:47:57.540] [trace] (ID:LUN 3:0) - Searching for object type 0, found type 0 at position 276
[2024-11-14 16:47:57.542] [trace] (ID:LUN 3:0) - Read SIMH header with class 0, value $0000001 at position 280
[2024-11-14 16:47:57.544] [trace] (ID:LUN 3:0) - Searching for object type 0, found type 0 at position 280
[2024-11-14 16:47:57.544] [trace] (ID:LUN 3:0) - Read SIMH header with class 0, value $0000000 at position 284
[2024-11-14 16:47:57.545] [trace] (ID:LUN 3:0) - Searching for object type 0, found type 1 at position 284
[2024-11-14 16:47:57.545] [trace] (ID:LUN 3:0) - Encountered filemark while spacing over blocks
```
s2p finds the data record at offset 268, which according to the s2psimh dump makes sense. But then it finds a data record also at offset 272, which is wrong. From the dump we can see that the next data record is at offfset 8468. s2p does not appear to skip the data record correctly, I will have a look at this.

Instead of the s2psimh dump of your file, can you please provide me a download link for the simh file you are using? I can then create a dump myself, and also have the file available for testing.
You say there are 4 files on this tape. Do the filenames appear in the dump? There are 3 short data blocks with what appears to be names in them at the start and 2 at the end. In between there are only regular data blocks of 8192 bytes. Is this the content you would expect? In case you know the names of the files on the tape and they are *not* included in these short blocks, are they included in the 8192 byte blocks? You can grep for them, e.g. with
```
s2psimh -d YOUR_TAP_FILE | grep NAME_OF_THE_FILE
```
If we assume that the filenames are visibile in the ASCII data of the dump they should be found.

The traffic between your driver and the emulated drive is fully covered by logging on trace level. A tool would not provide more information.
It would be nice, though, if there was a tool for your workstation that shows the traffic between your workstation and a *real* drive. For the Atari there is such a tool, maybe also for your workstation?

Thank you for running the s2pexec commands. The Sony and the DEC drive appear to support reverse-spacing. Since my drive also supports it, this feature appears to be quite common. But that's fine for SCSI2Pi, because I added reverse-spacing about 2 days ago to the issue_100 branch.

Any news on your web UI issue?

**Comment by uweseimet** [comment]
@Pacjunk I think I identified why s2p was out-of-sync. Please update and re-build issue_100 and run the directory test again. The s2p log should reveal the change.

**Comment by Pacjunk** [comment]
Only a little testing today - got a migraine!

Anyway, the directory listing seems to have worked correctly : 
[dir good.txt](https://github.com/user-attachments/files/17771206/dir.good.txt)

I tried to copy the first (small) file off the tape (VMS054.A), but this failed:
[copy bad.txt](https://github.com/user-attachments/files/17771215/copy.bad.txt)

I think I am using http://www.bitsavers.org/bits/DEC/vax/vms/TK50/aq-jp22f-be_vms_v5.4_bin_1of2_1990.tap for the data. Can't be 100% sure though - the file name is different. I downloaded it a long time ago.

**Comment by uweseimet** [comment]
So there is gradual progress. I always need to know the commit ID your tests are based on, please remember that.

If you are not sure which file you are using, please re-download it and compare it with your renamed file (e.g. with diff or bcmp), or use a different file. We have to ensure that I use the same file as you for my tests. As soon as it is ensured that we are using the same file, I would be interested in how the directory listing looks like.

When you say you copy a file off the tape, I assume that you mean you are essentially doing what "tar xf" does, i.e. extracting the archive contents and writing them to the filesystem?

**Comment by uweseimet** [comment]
@Pacjunk Thank you for checking this. I will try to make the SCSI2Pi block size support even more flexible than it already is, so that there is no upper limit anymore.

Regarding hard drives I have real drives with block sizes of up to 4096 bytes. For emulated tape drives the configured (or selected by the driver, see my previous comment) block size must be identical to the record size of the simh file.

**Comment by uweseimet** [comment]
Except for having to be a multiple of 4 bytes (according to the SCSI standard) the tape drive block size is now completely flexible. When there are read/write requests for a variable block size (this size can be bigger than the default block size), SCSI2Pi transfers and reads/writes the data in multiples of the default block size. This is reflected in the log: The bigger the default tape block size, the less read/write operations are needed. But the final result is always the same.

**Comment by Pacjunk** [comment]
I cannot compile now. I start the compilation and it goes for probably 90 minutes on the one file then:

```
g++ -O0 -g -DDEBUG -std=c++20 -iquote . -D_FILE_OFFSET_BITS=64 -DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL -MD -MP -Wall -Wextra -Wno-psabi  -DBOARD_FULLSPEC -DBUILD_SCHD -DBUILD_SCMO -DBUILD_SCCD -DBUILD_SCTP -DBUILD_SCDP -DBUILD_SCLP -DBUILD_SCHS -DBUILD_SAHD -DBUILD_STORAGE_DEVICE -DBUILD_DISK -c command/command_dispatcher.cpp -o obj/command_dispatcher.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
It seems to use most of the CPU and memory.

I followed your installation instructions and added: **export CXXFLAGS="clang++"**
This just generated errors as it just adds clang++ as a parameter, so you get **"g++** clang++ ..." and of course g++ doesn't know what to do with this.

I tried grabbing one of the build lines and substituted g++ with clang++ and this worked to build that one module. 

I don't know enough about makefiles understand how to fix this, so I just edited the Makefile to change g++ to clang++

I'm yet to see if this works.

**Comment by Pacjunk** [comment]
Build seems to complete (although it seemed to rebuild nearly everything). I will test later...

**Comment by Pacjunk** [comment]
Well that went badly - Can't even mount the tape now (can't find the label). Build c826343

Blocksize unset :
[mount1.txt](https://github.com/user-attachments/files/17783649/mount1.txt)

Blocksize set to 8k :
[mount8k.txt](https://github.com/user-attachments/files/17783651/mount8k.txt)

**Comment by uweseimet** [comment]
```
[trace] (ID:LUN 3:0) - Read SIMH header with class 0, value $0000000 at position 264
[debug] (ID 3) - MEDIUM ERROR (Sense Key $03), READ ERROR (ASC $11), ASCQ $00
```
I'll check this.

**Comment by uweseimet** [comment]
>Well that went badly - Can't even mount the tape now (can't find the label). Build https://github.com/uweseimet/scsi2pi/commit/c82634332d422c314cca29bcd3ec2f31654caa3b

This should be fixed with the latest issue_100 branch. I could reproduce this problem with the in process test tool and the same file that you are using.

**Comment by Pacjunk** [comment]
OK, using build 3a27cf7, mount now works again, and I successfully did a directory listing of the tape.

Copying of a file from the tape still fails: 
[copy.txt](https://github.com/user-attachments/files/17788484/copy.txt)

If I then do a directory listing of the tape (after the copy), it also fails : 
[dir.txt](https://github.com/user-attachments/files/17788485/dir.txt)

Don't know why it works before the copy, but fails afterwards.

**Comment by uweseimet** [comment]
@Pacjunk OK; thank you. Before getting back to you I will first work on #102, because with this functionaliy testing will become much easier. You can then simply generate a script file with all commands sent by your driver, and I can re-play these commands on my PC, as if I were using the same hardware as you. At least that's the idea of #102.

**Comment by uweseimet** [comment]
@Pacjunk I could easily reproduce your issue, because the commands sent by your driver do not vary much. These two s2pexec commands reproduce the bug:
```
-c 11:00:00:7f:ff:00
-c 08:00:00:20:00:00
```
Translation: Skip all filemarks and then read the first data record.

The latest issue_100 branch fixes the bug. Compiling will take longer again this time because some central header files have changed.

issue_100 now also contains the changes for #102, which will make testing much easier. In order to profit from these changes, this is what I would like you to do:

1. Update your log pattern (either on the command line or in /etc/s2p.conf) to "[%^%l%$] %v".
2. During testing always have s2p create a script for s2pexec, with all commands and data received. The new -s option will do that (please read #102) for details:
```
s2p -s /tmp/script.txt ...
```
As always, you can also add this to /etc/s2pexec:
```
script_file=/tmp/script.txt
```
3. Whenever something goes wrong, please attach the logfile and the matching script file. When I execute this script with the same image file as you, I should run into exactly the same problem as you. If this works as expected it will be a big help with testing.

**Comment by Pacjunk** [comment]
I get a failure when trying to compile...

```
clang++ -O0 -g -DDEBUG -std=c++20 -iquote . -D_FILE_OFFSET_BITS=64 -DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL -MD -MP -Wall -Wextra -Wno-psabi  -DBOARD_FULLSPEC -DBUILD_SCHD -DBUILD_SCMO -DBUILD_SCCD -DBUILD_SCTP -DBUILD_SCDP -DBUILD_SCLP -DBUILD_SCHS -DBUILD_SAHD -DBUILD_STORAGE_DEVICE -DBUILD_DISK  -o bin/s2p obj/s2p_core.o obj/s2p_parser.o obj/s2p_thread.o obj/s2p.o lib/libcommand.a lib/libbus.a lib/libcontroller.a lib/libdevice.a lib/libshared.a  -lpthread -lprotobuf
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
make: *** [Makefile:390: bin/s2p] Error 254
```

**Comment by uweseimet** [comment]
@Pacjunk This appears be an issue with not enough memory for linking. It is not the compile but the link stage.
Please try g++ instead of clang++, or try an alternative linker as explained on https://github.com/uweseimet/scsi2pi/wiki/Compilation-Instructions. Or, at least temporarily, edit the Makefile, search for "-g" and remove it. Note that in any case you need to run "make clean" before trying again.

**Comment by Pacjunk** [comment]
I changed to clang because g+ was using too much memory. I'm looking at configuring a spare Pi 3B to do the job. I was going to use the 64 bit pre-built image for PiSCSI, then loading SCSI2Pi over the top. Is this the best option, or should I use 32bit, or another flavour of raspbian?

**Comment by Pacjunk** [comment]
Removing -g didn't help. Currently rebuilding without debug. I suppose 32 or 64 bit doesn't matter too much. The 3B only has 1GB memory.

**Comment by uweseimet** [comment]
1 GB should be enough. The build failed on a 512 MB Pi, didn't it? What should also work on a 512 MB Pi is adding some swap space, e.g with a swap file of about 512 MB.

**Comment by Pacjunk** [comment]
Yep 512. ZeroW. Reluctant to add swap - shortens life of SD card! (and makes things even slower)

**Comment by uweseimet** [comment]
Yes, swap space is never that nice, but sometimes a last resort.

**Comment by uweseimet** [comment]
@Pacjunk When resuming your tests please ensure to update to the latest available issue_100 branch. It contains fixes for exotic functions (but your driver might use them, you never know). The logging of the tape position has also been improved, which is important because many of the issues you reported were causes by s2p being out-of-sync with the file contents.

**Comment by Pacjunk** [comment]
Compiled OK without debug. Build e31d416

Problem is it's broken again. Cannot mount the tape...

[mount.txt](https://github.com/user-attachments/files/17808224/mount.txt)
[script.txt](https://github.com/user-attachments/files/17808225/script.txt)

**Comment by uweseimet** [comment]
@Pacjunk Has there been any change with your setup? When I compare the log of the successful mount with the latest log I find that a READ POSITION command in the new log at line 155, whereas in the old log in the corresponding line 157 there is a MODE SENSE.
Before this line all data transferred before are identical. This IMO means that nothing has effectively changed as far as the behavior of s2p is concerned, but nevertheless your driver sends different commands.

**Comment by Pacjunk** [comment]
No doing exactly the same. Only thing different is compiling without debug. I can run the test again if you like.

**Comment by uweseimet** [comment]
Debug should not matter, but if nothing else has changed this would have to be verified. Even though it takes some time I would like to ask you to run the mount test again with commit ID 3a27cf7 and to attach the log. I recommend to do this in a separate folder, e.g. like this:
```
cp -r -p scsi2pi.git scsi2pi.git.test
cd scsi2pi.git.test
make clean
git co 3a27cf7
```
Then run make with the same settings you used last time for your current build.

Note that the latest s2p warns about unknown parameters, and you are still using "caching_mode=write-through:3" as a global parameter, which is invalid. I suggest you remove this parameter.

**Comment by Pacjunk** [comment]
Just ran the test again. Logs attached:
[mount.txt](https://github.com/user-attachments/files/17812304/mount.txt)
[script.txt](https://github.com/user-attachments/files/17812309/script.txt)

**Comment by uweseimet** [comment]
So no change, i.e. my previous comment applies, i.e. this needs to be verified with commit ID 3a27cf7 because the logs say that s2p does the same as before,

**Comment by Pacjunk** [comment]
If I do `git checkout 3a27cf7` it says that I'm in headless mode. Shouldn't it replace some files?

**Comment by uweseimet** [comment]
It has, it is not on the HEAD of the source tree anymore, that's what the message means. You can check the current commit ID with " git log --abbrev-commit".

**Comment by Pacjunk** [comment]
OK, just used to git pull displaying changed files. Thought it might display something similar. Apparently not.
Building now - if I'm lucky it might finish before midnight!

**Comment by uweseimet** [comment]
Just take your time. Just to ensure that we are in sync: The idea is to verify that it is reproducable that your driver interacts differently with the two commits. The logs say that the behavior of s2p has not changed, and they contain the complete flow of data. So what has actually changed, or what I am missing that's not in the logs?

**Comment by uweseimet** [comment]
Thank you for re-compiling.

At least the results are consistent. I have no idea yet why your driver uses different commands even though the logfiles do not indicate any difference, up to the point where your driver suddenly uses READ POSITION.

**Comment by Pacjunk** [comment]
Still no go. Note that the mount is with a clean boot of the OS - no prior operations on that device.

[mount.txt](https://github.com/user-attachments/files/17824847/mount.txt)
[mount script.txt](https://github.com/user-attachments/files/17824849/mount.script.txt)

**Comment by uweseimet** [comment]
@Pacjunk There is still a MEDIUM ERROR being reported. I will try to reproduce this.

**Comment by uweseimet** [comment]
@Pacjunk OK, with my setup this is fixed now in the latest issue_100 branch. Please update and recompile. I will add a unit test to cover what you found later.

**Comment by uweseimet** [comment]
Both errors are related to the tape drive block size being 512 bytes, but the simh record size being 8192 bytes. Lauching s2p with -b 8192 should fix this. But technically it should be possible to read (but not to write) 8192 byte records even with a tape block size of 512 bytes. I am already working on this.
```
trace] (ID:LUN 3:0) - Actual block length of 8192 byte(s) does not match requested length of 512 byte(s)
```

**Comment by uweseimet** [comment]
@Pacjunk Your simh files contain blocks of different sizes, 80 (directory) and 8192 bytes (data). The latest errors are reported for block sizes of 8192 bytes, not for blocks of 80 bytes, see the logfile snippet in my last comment.
Real tape drives support almost any block size. The newer the drive, the bigger the default block size. Using a lot of small blocks for large amounts of data is inefficient, because each block requires meta data, which also use space on the tape. With simh files it is the same: Each data block has 8 bytes of meta data. Markers usually need 4 bytes of data. This also means that, just like with a real tape, you cannot exactly tell the capacity of a tape. The number of blocks and meta data differs on the driver etc.

Dealing with block size mismatches is not that easy, because the standard has special rules. Requesting less bytes than the actual block size is usually fine, unless the driver requests an error to be raised by setting a flag in the SCSI command. And the driver may specifiy either the number of bytes or the number of blocks to transfer. When you also take into account that s2p shall *not* consider it an error when a multiple (e.g. 8192) of a tape driver block size (e.g. 512) is requested, there are quite a lot of cases that have to be dealt with.
For verything you find (and much more) I am in the process of adding unit tests. Tapes are more difficult to test than hard drives.

Thank you for the link, but for my implementation I use the original SCSI specificiations. Usually SCSI-2, but also newer ones, which are sometimes more precise. Furthermore, s2p also implements some commands from newer standards than SCSI-2.
The SCSI standard is still being developed further, because SCSI is also a hardware-independent software protocal used in modern peripherals.

**Comment by uweseimet** [comment]
@Pacjunk I don't have the time today to address the latest issue. First I want to update/extend the unit tests. But my expectation is that with "-b 8192" the behavior will improve. Can you please test this with your current binary, before updating the branch? If the behavior is better than before, please create a copy of this branch as a backup. Then please update your sources, re-compile and test with the latest branch, again with "-b 8192".
Please attach the respective logs and scripts. If the mount and dir tests are still working, no logs/scripts are needed for them.
Thank you!

**Comment by Pacjunk** [comment]
With the block size at 8192, I managed to copy the first file (VMS054.A) successfully from the tape. It was just under a megabyte. I tried the second file, which started but ran out of disk space, but this still proved that it located the correct file to transfer. Accessing the file when the tape is mounted foreign fails, and init still crashes the OS.

I am rebuilding with the latest now...

**Comment by Pacjunk** [comment]
No difference with the latest build. Still problem with init crashing the OS - but I suppose you want to get read operations working first.  Although I can copy the backup savesets from tape to disk and then extract them, the usual operation is to extract them directly from tape. This bit doesn't work. The tape is mounted in a different way, but still reads the label. When I try to list the contents of the tape, this is what I get:

[ForeignList.txt](https://github.com/user-attachments/files/17839991/ForeignList.txt)
[ForeignList Script.txt](https://github.com/user-attachments/files/17839993/ForeignList.Script.txt)

**Comment by uweseimet** [comment]
@Pacjunk Thank you for the latest tests. Step by step things are improving. As usual, I will check your logs and get back to you.

**Comment by uweseimet** [comment]
@Pacjunk This time it was easy to find out what was wrong. Please try again with the latest issue_100 branch. Note that until further notice the "-b 8192" option is needed.
You will see an error message saying "Actual block length of 80 byte(s) does not match requested length of 90 byte(s)". This is because your driver is requesting 90 bytes this time, but the record size is 80. I assume that's intentional, and your driver will react in a meaningful way on the SCSI error it receives. We'll learn more in your next log/script.

**Comment by Pacjunk** [comment]
50ec59c 
Different error message (says the tape is not in ANSI format), but still no go.
[ForeignList.txt](https://github.com/user-attachments/files/17843007/ForeignList.txt)
[ForeignList Script.txt](https://github.com/user-attachments/files/17843009/ForeignList.Script.txt)

**Comment by uweseimet** [comment]
Now the driver requests details on the error message, which it did not do before. I will have to check whether the error information I send is correct. Tape drive have a quite special error handling, not used by hard drives.
In the meantime, can you also test writing to a tape?

**Comment by uweseimet** [comment]
For further evaluation I need additional logging. Can you please update and run your test again?

**Comment by Pacjunk** [comment]
Here you go...
[ForeignList.txt](https://github.com/user-attachments/files/17844019/ForeignList.txt)
[ForeignList Script.txt](https://github.com/user-attachments/files/17844022/ForeignList.Script.txt)

Also, this is an attempt to write a file to the tape:
[writefile.txt](https://github.com/user-attachments/files/17844035/writefile.txt)
[writefile script.txt](https://github.com/user-attachments/files/17844036/writefile.script.txt)

I am currently creating a physical tape containing the same contents as the .tap file we are using. It won't be absolutely identical, but will be close enough. I have tested these operations on simh, but then simh doesn't support SCSI tape drives, so I will create a physical tape just to reassure myself that these commands work in the real world.

**Comment by uweseimet** [comment]
@Pacjunk Yes, testing with a real drive is a good idea.

But I may have found a bug: The log of ForeignTest shows that in the error data returned by s2p ILI (Invalid Length Indicator) is set, and the INFORMATION field is the requested length minus the actual length, = 10. This is all fine, but the error code MEDIUM ERROR is wrong, just checked this with the specification.
I updated the code, please update and re-test only ForeignTest.

**Comment by Pacjunk** [comment]
Latest (still fails):
[ForeignList.txt](https://github.com/user-attachments/files/17844541/ForeignList.txt)
[ForeignList Script.txt](https://github.com/user-attachments/files/17844543/ForeignList.Script.txt)

**Comment by uweseimet** [comment]
Now your driver simply stops sending more commands. Don't know yet what this means.

**Comment by uweseimet** [comment]
Regarding your write test: I think I found a bug, please update and re-test.

**Comment by Pacjunk** [comment]
Still failed:
[write file.txt](https://github.com/user-attachments/files/17845103/write.file.txt)
[write file script.txt](https://github.com/user-attachments/files/17845105/write.file.script.txt)

Does the .tap file automatically extend as data is written to it?

**Comment by uweseimet** [comment]
No, it does not. This is something I have already considered, maybe as an option, but not yet implemented.

**Comment by uweseimet** [comment]
No, it does not. This is something I have already considered, maybe as an option, but not yet implemented.

**Comment by uweseimet** [comment]
@Pacjunk I found a bug that affected ForeignTest: The ILI bit was coded at the wrong position, which means the driver would not know what had actually happened when 90 bytes were requested.
This is fixed now, please update your issue_100 branch and try again.

**Comment by uweseimet** [comment]
@Pacjunk In case you have time for it, issue_104 contains a change that addresses the fact that currently "-b 8192" is strictly required. If you find the time, after testing with the latest issue_100 branch, please create a copy of your checked out git folder, switch to this folder and run "git checkout issue_104". Then re-compile in the new branch and verify whether everything works (as far as it already does) regardless of whether you say "-b 8192" or not.

**Comment by Pacjunk** [comment]
The only doco I've seen talks about the SCSI API for the OS. Some other doco does talk about the ANSI standard used for tape layout but is pre-SCSI (http://www.bitsavers.org/pdf/dec/vax/vms/4.4/AI-Y506B-TE_VMS_4.4_Disk_and_Tape_Operations_198604.pdf appendix B). I ran the tests in the latest Issue100 branch, and got the following:
[ForeignList.txt](https://github.com/user-attachments/files/17863584/ForeignList.txt)
[ForeignList Script.txt](https://github.com/user-attachments/files/17863594/ForeignList.Script.txt)

**Comment by uweseimet** [comment]
Fixing the wrong bit did not change anything. Now the time has come to ask your real drive what it does when it stumbles upon a block size mismatch.
Can you please run your ForeignList.Script.txt with s2pexec against your device? In order to enable trace mode insert "-L trace" as the first iline:
```
-L trace
-i 3:0 -c 00:00:00:00:00:00
-i 3:0 -c 12:00:00:00:24:00
-i 3:0 -c 1a:00:00:00:ff:00
-i 3:0 -c 1a:00:00:00:ff:00
-i 3:0 -c 15:00:00:00:0c:00 -d 00:00:10:08:00:00:00:00:00:00:00:00
-i 3:0 -c 1a:00:00:00:ff:00
-i 3:0 -c 34:00:00:00:00:00:00:00:00:00
-i 3:0 -c 1a:00:10:00:ff:00
-i 3:0 -c 1a:00:50:00:ff:00
-i 3:0 -c 08:00:00:00:5a:00
-i 3:0 -c 03:00:00:00:13:00
```
This is the command to run:
```
>s2pexec < THE_SCRIPT_FILE_ABOVE > LOGFILE
```
LOGFILE will collect all responses, with the response to the offending READ(6) command and the respective REQUEST SENSE command at the end.

**Comment by Pacjunk** [comment]
My physical tape won't be exactly the same, but has the same label, the same files and content. There might be a few bytes different in the headers, but the blocks sizes should be the same. Just building s2pexec now.

**Comment by uweseimet** [comment]
Sounds good! We just need some content that reflects the the situation s2p stumbles upon. If need should be, the script can be extended to write the required data to the drive.

**Comment by Pacjunk** [comment]
Don't know what I'm doing wrong...
[1.txt](https://github.com/user-attachments/files/17868153/1.txt)

Only devices powered on were the Pi and the tape drive.

If I include the script for the mount part of it, then I get commands executing, but then it soon starts giving the error.
[2.txt](https://github.com/user-attachments/files/17868166/2.txt)

I tried it with the host powered up (initiator=6) but got the same bus not free errors

**Comment by uweseimet** [comment]
Looks as if the bus is blocked after MODE SELECT. I will have to check whether there is an issue with s2pexec. But I don't think that we need the MODE SELECT. Please run this script instead, which just contains what we really need:
```
-L trace
-i 3:0 -c 00:00:00:00:00:00
-i 3:0 -c 12:00:00:00:24:00
-i 3:0 -c 08:00:00:00:5a:00
-i 3:0 -c 03:00:00:00:13:00
-i 3:0 -c 08:00:00:00:5a:00
-i 3:0 -c 03:00:00:00:13:00
```

**Comment by Pacjunk** [comment]
I added the script from the mount command, because that was being done prior. This probably had a rewind in it. I have run your scripts again, but different results every time - I suppose the tape moves on, so different results.
[scriptout.txt](https://github.com/user-attachments/files/17868914/scriptout.txt)
[scriptout2.txt](https://github.com/user-attachments/files/17868915/scriptout2.txt)
[scriptout3.txt](https://github.com/user-attachments/files/17868917/scriptout3.txt)

I then mounted the tape with the OS, then ran your script:

**Comment by uweseimet** [comment]
I think it is best to not run anything before the script. No mount, nothing. Please try
```
-i 3:0 -c 00:00:00:00:00:00
-i 3:0 -c 12:00:00:00:24:00
-i 3:0 -c 01:00:00:00:00:00  -o 120
-i 3:0 -c 08:00:00:00:5a:00
-i 3:0 -c 03:00:00:00:13:00
-i 3:0 -c 08:00:00:00:5a:00
-i 3:0 -c 03:00:00:00:13:00
```
This should display the drive name (just to ensure that nothing is initially blocked), then rewinds with a timeout, then reads.

**Comment by Pacjunk** [comment]
scriptout.txt *is* a test with nothing run beforehand. 2 & 3 are subsequent runs. The only one where I did a mount beforehand was the host.txt.  Sorry, but I have already packed up the gear for the night. I will try to move the machine into the house tomorrow, so it is easier to test.

**Comment by uweseimet** [comment]
Sure. I also moved my Atari from a different room into my working room some time ago, because this is more convenient.

**Comment by uweseimet** [comment]
@Pacjunk This comment summarizes the open items from my previous comments.

In order to reduce the number of code paths I am working on, I updated issue_100 to address the "-b 8192" problem. I also merged https://github.com/uweseimet/scsi2pi/issues/104, i.e. appending to existing files is now supported as a non-default option.

scriptout.txt shows that your drive does *not* report details (ILI bit, information on the difference between expected and actual block size) on a read error. According to SCSI this information is optional, indeed. Your drive correctly signals that it does not provide this information by *not* setting the VALID bit in the response. s2p does, because some driver may require this data. Assuming that the script used for scriptout really reflects what's happening when your driver sends the offending READ command, the next step will be to modify s2p to not provide this information anymore.
Therefore I suggest these to be the next steps:

1. It would be helpful if we could run our custom scripts without having to run other commands (mount) before. Please run this script against your drive:
```
-i 3:0 -c 12:00:00:00:24:00
-i 3:0 -c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-i 3:0 -c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-i 3:0 -c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-i 3:0 -c 11:00:00:00:02:00
-i 3:0 -c 08:00:00:00:20:00
```
It writes 3 blocks of 4 bytes, then spaces back 2 blocks and tries to read a block with a size of 32 bytes. The position on the tape should not matter with this approach. Based on the output we can see whether this works, or whether the script has to be tweaked.
2. Update your issue_100 branch. Do not use "-b 8192" anymore, unless something that has been working before does not work anymore. There is no block size mismatch log message anymore, because we have learned that a block size mismatch can also happen during normal operation. The logfile still reflects what happened in the "ILI: 1, INFORMATION: X" line, and in the SCSI error that is logged.
3. The next step is using a modified version of s2p, which does not report read error details. Maybe these additional data confuse your driver, even though I would expect it to just ignore these data.
Modify your local cpp/base/primary_device.cpp and insert these lines in the HandleRequestSense() method at line 293. The line where the insert needs to happen is 295, right at the beginning of the method:
```
valid = false;
ili = false;
```
Re-compile and run ForeignTest. The resulting log must *not* contain this line anymore:
```
[trace] (ID:LUN 3:0) - ILI: 1, INFORMATION: 10

```
4. This test is independent of the previous steps: Please run the write test with an image file big enough to avoid end-of-media errors.

**Comment by Pacjunk** [comment]
Still having trouble with s2pexec - when I get the bus error, I have to power cycle the tape drive.
I changed your script to:
```
-L trace
-i 3:0 -c 12:00:00:00:24:00 -o 90 # INQUIRY
-i 3:0 -c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90 # Write a 4 byte block
-i 3:0 -c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90 # One more
-i 3:0 -c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90 # One more
-i 3:0 -c 11:00:ff:ff:fe:00 -o 90 # Space 2 blocks back
-i 3:0 -c 08:00:00:00:20:00 -o 90 # Try to read 32 bytes from a block with only 4 bytes
```
Got the following results:
[out.txt](https://github.com/user-attachments/files/17878727/out.txt)

**Comment by uweseimet** [comment]
@Pacjunk Is there a reproducable sequence of commands that causes the bus to hang? According to the log the script execution was successful, i.e. no errors were reported when writing the blocks and spacing back. When trying to read the block your drive reports an error. What's missing is the detailed error information by s2pexec. I will check this.

**Comment by Pacjunk** [comment]
I just added more timeouts. Seemed to help. The log I supplied was the only one that didn't cause a problem. Can also confirm that the tape was written to as it is now corrupt. (I did use a new tape for this because I knew it would destroy it). Haven't got to the other tests yet...

**Comment by uweseimet** [comment]
@Pacjunk Yes, a tape reserved this purpose is needed, indeed ;-).

 I updated s2pexec in the issue_100 branch to display the REQUEST SENSE results. Please run your script again. What we can already see in the previous log is that the ILI bit and the information field were not set by your drive. This is consistent with the previous results, and the reason for putting item 3. on my list.

**Comment by Pacjunk** [comment]
should it have the "-i 3:0" in front of it?

**Comment by uweseimet** [comment]
s2pexec remembers the -i setting, i .e. there is no need to repeat it.

**Comment by Pacjunk** [comment]
Build errors for s2pexec...

```
shared/s2p_util.cpp:239:76: error: invalid operands to binary expression ('std::span<const std::byte, 4294967295>::element_type' (aka 'const std::byte') and 'std::byte')
    const string &s = FormatSenseData(static_cast<sense_key>(sense_data[2] & byte { 0x0f }),
                                                             ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
shared/s2p_util.cpp:242:24: error: invalid operands to binary expression ('std::span<const std::byte, 4294967295>::element_type' (aka 'const std::byte') and 'std::byte')
    if ((sense_data[0] & byte { 0x80 }) == byte { 0 }) {
         ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
shared/s2p_util.cpp:246:75: error: invalid operands to binary expression ('std::span<const std::byte, 4294967295>::element_type' (aka 'const std::byte') and 'std::byte')
    return s + fmt::format(", ILI: {0}, INFORMATION: {1}", (sense_data[2] & byte { 0x20 }) != byte { 0 } ? "1" : "0",
                                                            ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
3 errors generated.
make: *** [Makefile:357: obj/s2p_util.o] Error 1

```

**Comment by uweseimet** [comment]
This is which OS (bullseye/bookworm 16/32 bit) and compiler version?

Please try whether instead of
```
    if ((sense_data[0] & byte { 0x80 }) == byte { 0 }) {
```
this works (even though it does not work with MY compiler):
```
   if (!(sense_data[0] & 0x80)) {

```
But before doing that, please update your sources.

**Comment by uweseimet** [comment]
@Pacjunk I think I found a compiler-indepedent solution. Please once more update your issue_100 sources, so that you get my latest change.

**Comment by Pacjunk** [comment]
Bullseye, 32 bit

```
clang++ -O3 -Wall -DNDEBUG -std=c++20 -iquote . -D_FILE_OFFSET_BITS=64 -DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL -MD -MP -Wall -Wextra -Wno-psabi  -DBOARD_FULLSPEC -DBUILD_SCHD -DBUILD_SCMO -DBUILD_SCCD -DBUILD_SCTP -DBUILD_SCDP -DBUILD_SCLP -DBUILD_SCHS -DBUILD_SAHD -DBUILD_STORAGE_DEVICE -DBUILD_DISK -c shared/s2p_util.cpp -o obj/s2p_util.o
shared/s2p_util.cpp:239:76: error: invalid operands to binary expression ('std::span<const std::byte, 4294967295>::element_type' (aka 'const std::byte') and 'std::byte')
    const string &s = FormatSenseData(static_cast<sense_key>(sense_data[2] & byte { 0x0f }),
                                                             ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:357: obj/s2p_util.o] Error 1

```

**Comment by uweseimet** [comment]
Thank you. I assume the latest change will work for all compilers. The bullseye compilers are quite old.

**Comment by uweseimet** [comment]
Very strange: I wonder what the problem with my tape drive is. It neither works with my Atari nor with Linux anymore, even after applying a cleaning tape.
But just for fun I tried sending the latest script to it, and it actually worked. The drive reported
```
00000000  f0:00:20:00:00:00:1c:0b:00:00:00:00:00:00        '.. ...........'
```
It tells me that the operation failed because of a block size mismatch and that I tried to read 28 ($1c) bytes more than available.

**Comment by Pacjunk** [comment]
Still no go. Works on bookworm though. Looks like I might be ditching the pi zero!

**Comment by uweseimet** [comment]
What's the error message now?

**Comment by uweseimet** [comment]
By the way, just for this test you can replace the if condition with "true" and "(sense_data[2] & byte { 0x20 }) != byte { 0 }" also with "true".

**Comment by uweseimet** [comment]
I updated issue_100 once more, after verifying that s2p_util.cpp now compiles on my Pi Zero with bullseye. Please update your sources and recompile. Note that this time recompiling may take longer, because of a header file change.

**Comment by Pacjunk** [comment]
Latest s2pexec output (with that extra line):
[out.txt](https://github.com/user-attachments/files/17891613/out.txt)

**Comment by Pacjunk** [comment]
Next test was removing the 8192 blocksize in the config file. Seems to work as expected.

Next was trying to read the backup saveset with tape mounted foreign (still failed):
[foreignlist script.txt](https://github.com/user-attachments/files/17891676/foreignlist.script.txt)
[foreignlist.txt](https://github.com/user-attachments/files/17891677/foreignlist.txt)

Next was trying to write a file to the tape. File is about 30 bytes. One 512 block on disk. Tape file size is 64KB. Failed...
[writefile script.txt](https://github.com/user-attachments/files/17891684/writefile.script.txt)
[writefile.txt](https://github.com/user-attachments/files/17891685/writefile.txt)

**Comment by Pacjunk** [comment]
A bit of good news... The tape initialisation (labelling) that was crashing my OS now works!  This was working a week(?) ago, then started crashing, but now works as expected. Changed label from TEST55 to TEST33 which is reflected in the log.

[init script.txt](https://github.com/user-attachments/files/17891708/init.script.txt)
[init.txt](https://github.com/user-attachments/files/17891709/init.txt)

**Comment by uweseimet** [comment]
Thank you for the extensive tests. Please always add the commit ID. This time I assume it was 82a1b67, please confirm.

Regarding the offending READ command, your drive has returned:
```
f0:00:20:00:00:00:1c:12:00:00:00:00:00:00
```
0nly the first 6 bytes matter, and they say that it was attempted to read 28 bytes more than available.
My drive reports the same:
```
f0:00:20:00:00:00:1c:0b:00:00:00:00:00:00 
```
And s2p also returns the right data:
```
f0:00:20:00:00:00:1c:0a:00:00:00:00:00:00
```
This means that from the sense data error handling perspectiv we are fine.

Regarding the init script, I assume it is working (again) because I fixed some issues in the WRITE command.

write.txt still shows (at the end) that end-of-partition is hit while searching for the next block on the file. But there is no next block. Can you please add the s2psim output for this file? I would like to see which SIMH data the file contains.

Regarding ForeignTest, the end of the log shows that the ILI bit is not set, which is wrong. I will check this.

**Comment by uweseimet** [comment]
WRT foreign test and the ILI bit: The bit was set correctly, the log output was broken. This is fixed in the latest issue_100 branch.
Unfortunately this means that it is not clear yet why foreign test fails and stops after receiving the block size mismatch error data.

These will be my next steps:

1. I will try to reproduce the issue with write.txt, as soon as you have provided the SIMH data of the image file.
2. I will extend s2psimh, so that you can create SIMH files with. I sometimes need files with a particular content for testing.
3. I will have to rewrite the spacing code. The unit tests show that they are some cases not covered correctly, and the current code is quite a mess.

**Comment by Pacjunk** [comment]
I can attach the .tap file I used for the write here if you want. Its only 64KB.

**Comment by uweseimet** [comment]
I wanted to save GitHub resources, and the SIMH log is smaller ;-). But the file will also work, of course.

**Comment by Pacjunk** [comment]
Here you go...   
[1.tap.dmp](https://github.com/user-attachments/files/17892948/1.tap.dmp)
(just strip off the ".dmp" bit).

I'm going to be away for the next couple of days, so won't be able to do any testing. Maybe in 48 hours.

**Comment by uweseimet** [comment]
OK! I have enough tasks to work on in the meantime ;-). See you!

**Comment by uweseimet** [comment]
I will use this comment to document (and update) the status until your return.

1. Regarding write.txt: There appears to be a mismatch between your output and the output I get when using your script with the tap file you provided. The file has an end-of-data object at the end, and my output confirms that s2p detects this correctly while spacing:
```
[trace] (ID:LUN 3:0) - Read SIMH meta data with class 7, value $3533250 at position 456
[trace] (ID:LUN 3:0) - Found SCSI2Pi private marker for object type 3 at position 456
[trace] (ID:LUN 3:0) - Found object type 3 at position 456, length 0, spaced over 0 object(s)
[trace] (ID:LUN 3:0) - Encountered end-of-data at position 456 while spacing over object type0
[debug] (ID 3) - BLANK CHECK (Sense Key $08), NO ADDITIONAL SENSE INFORMATION (ASC $00), ASCQ $00
```
In your log output s2p detects end-of-partition instead at the same position in the file:
```
[trace] (ID:LUN 3:0) - Read SIMH meta data with class F, value $fffffff at position 456
[trace] (ID:LUN 3:0) - Found object type -1 at position 456, length 0, spaced over 0 object(s)
[trace] (ID:LUN 3:0) - Encountered end-of-partition at position 460 while spacing
[debug] (ID 3) - MEDIUM ERROR (Sense Key $03), NO ADDITIONAL SENSE INFORMATION (ASC $00), ASCQ $00
```
Therefore a wrong error message is returned, even though the file offset is 456 in both cases. This means that we are using different files. The file you provided has an end-of-data marker at the end:
```
Offset 456 ($1c8): Class 7, private marker (SCSI2Pi end-of-data object)
```
Please repeat this test after updating your issue_100 sources. (Do not forget to provide the commit ID next time). Use a blank image file for this test, and ensure that after the error has been reported the file is not used for anything else anymore. I suggest the you also verify with s2psimh whether there is an end-of-data object at the end or not. After writing data to a file s2p ensures that there is an end-of-data object. This means that end-of-partition should only be reported when the file is too small, which is not the case here.

**Comment by Pacjunk** [comment]
Sorry, I haven't had time to test. My son has been in hospital twice this week (still there), so catching up on sleep. Hopefully soon...

**Comment by uweseimet** [comment]
@Pacjunk Thank you for your note. I hope that your son will be better soon!

**Comment by Pacjunk** [comment]
Some tests with foreignlist. Note I can't start with a blank file because I cannot write any files to the emulated tape drive yet! I can initialise the tape, but the command I use reads a file on the tape, and that file cannot exist as we haven't got to the stage of writing files yet.

Running the output script on a real tape. This tape is not and cannot be identical, but has the same contents.
[foreignlist script exec.txt](https://github.com/user-attachments/files/17968140/foreignlist.script.exec.txt)

Script output:
[foreignlist script.txt](https://github.com/user-attachments/files/17968141/foreignlist.script.txt)

s2p output:
[foreignlist.txt](https://github.com/user-attachments/files/17968142/foreignlist.txt)

**Comment by Pacjunk** [comment]
If I initialise a blank (zeroed) file, I get the following:

```
Offset 0 ($0): Class 0, good data record, record length 80 ($50)
Offset 88 ($58): Class 0, good data record, record length 80 ($50)
Offset 176 ($b0): Class 0, good data record, record length 80 ($50)
Offset 264 ($108): Class 0, tape mark
Offset 268 ($10c): Class 0, tape mark
Offset 272 ($110): Class 0, good data record, record length 80 ($50)
Offset 360 ($168): Class 0, good data record, record length 80 ($50)
Offset 448 ($1c0): Class 0, tape mark
Offset 452 ($1c4): Class 0, tape mark
Offset 456 ($1c8): Class 7, private marker (SCSI2Pi end-of-data object)

```

As far as I know, the double tape mark signifies the end of the tape, so why is there more data after the double tape mark?
The data seems like valid entries:

```
Offset 0 ($0): Class 0, good data record, record length 80 ($50)
00000000  56:4f:4c:31:54:45:53:54:20:20:20:20:20:20:20:20  'VOL1TEST        '
00000010  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000020  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000030  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000040  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:33  '               3'
Offset 88 ($58): Class 0, good data record, record length 80 ($50)
00000000  48:44:52:31:20:20:20:20:20:20:20:20:20:20:20:20  'HDR1            '
00000010  20:20:20:20:20:54:45:53:54:20:20:30:30:30:31:30  '     TEST  00010'
00000020  30:30:30:30:30:30:31:30:30:30:32:34:33:33:36:30  '0000001000243360'
00000030  32:34:33:33:36:20:30:30:30:30:30:30:44:45:43:46  '24336 000000DECF'
00000040  49:4c:45:31:31:41:20:20:20:20:20:20:20:20:20:20  'ILE11A          '
Offset 176 ($b0): Class 0, good data record, record length 80 ($50)
00000000  48:44:52:32:46:30:30:30:30:30:30:30:30:30:30:20  'HDR2F0000000000 '
00000010  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000020  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000030  20:20:30:30:20:20:20:20:20:20:20:20:20:20:20:20  '  00            '
00000040  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
Offset 264 ($108): Class 0, tape mark
Offset 268 ($10c): Class 0, tape mark
Offset 272 ($110): Class 0, good data record, record length 80 ($50)
00000000  45:4f:46:31:20:20:20:20:20:20:20:20:20:20:20:20  'EOF1            '
00000010  20:20:20:20:20:54:45:53:54:20:20:30:30:30:31:30  '     TEST  00010'
00000020  30:30:30:30:30:30:31:30:30:30:32:34:33:33:36:30  '0000001000243360'
00000030  32:34:33:33:36:20:30:30:30:30:30:30:44:45:43:46  '24336 000000DECF'
00000040  49:4c:45:31:31:41:20:20:20:20:20:20:20:20:20:20  'ILE11A          '
Offset 360 ($168): Class 0, good data record, record length 80 ($50)
00000000  45:4f:46:32:46:30:30:30:30:30:30:30:30:30:30:20  'EOF2F0000000000 '
00000010  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000020  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000030  20:20:30:30:20:20:20:20:20:20:20:20:20:20:20:20  '  00            '
00000040  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
Offset 448 ($1c0): Class 0, tape mark
Offset 452 ($1c4): Class 0, tape mark
Offset 456 ($1c8): Class 7, private marker (SCSI2Pi end-of-data object)

```

You are not writing two tape marks instead of one?

**Comment by uweseimet** [comment]
First of all: Please do provide the commit ID you have tested ;-). I commit quite often, and I need to know which sources your tests are based on.

The private end-of-data marker is automatically created by s2p. The two tape marks written by your driver are specific to your driver. s2p may not assume these to always be there and have a particular meaning. tar and drivers for other platforms handle this differently.

Regarding a blank file: What I meant is that it should be empty before you initialize it. This means it should not contain anything else but the well-defined data you have dumped above, with the two tape marks at the end.

I will get back to you as soon as I have analyzed the latest logs.

**Comment by Pacjunk** [comment]
I did give the build number (beginning of post)

**Comment by uweseimet** [comment]
Yes, I just noticed that. I'm sorry for missing it.

**Comment by uweseimet** [comment]
Regarding your test, the sense data returned by your driver include custom information not covered by the SCSI specification. I have tweaked s2p to also return some of these data, let's see what happens.
Please update your issue_100 sources and run the test again.

**Comment by Pacjunk** [comment]
Build f15e373

I've changed to the Pi 3B - sick of 3 hour+ rebuilds due to low memory. Seems to run s2p faster as well!

No real change in latest logs. Attached...
[foreignlist.txt](https://github.com/user-attachments/files/17988128/foreignlist.txt)
[foreignlist script.txt](https://github.com/user-attachments/files/17988130/foreignlist.script.txt)

**Comment by uweseimet** [comment]
Yes, the transfer rates depend on the CPU and on how fast/how often per time unit the GPIO port can be accessed. The latter is probably even more important than the CPU. I have optimized this, which in one reason for the higher throughput then with the PiSCSI software.

Regarding your test I am still unsure what the relevant difference between s2p and your drive is. Can you please run this script with s2pexec against your drive?
```
-L trace -i 3:0
-c 12:00:00:00:24:00 -o 90
-c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-c 11:00:ff:ff:fe:00 -o 90
-c -n 08:00:00:00:20:00 -o 90
-c 03:00:00:00:ff:00
```
It is slightly different than the one before wrt getting the sense data.

**Comment by Pacjunk** [comment]
Here you go... 
[test.txt](https://github.com/user-attachments/files/17991131/test.txt)

It is not easy for me to get the other tape drive at the moment. Maybe tomorrow...

**Comment by Pacjunk** [comment]
Yes, the tape was write protected. I assumed you were doing a test similar to the foreignlist test which was only reading the tape - and I don't want some strange script corrupting that tape.  I will re-run the test with a scratch tape.

**Comment by uweseimet** [comment]
Thank you. I'm afraid there was a typo in the script. Can you please try again with:
```
-L trace -i 3:0
-c 12:00:00:00:ff:00
-c 00:00:00:00:00:00
-c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-c 0a:00:00:00:04:00 -d 01:02:03:04 -o 90
-c 11:00:ff:ff:fe:00 -o 90
-n -c 08:00:00:00:20:00 -o 90
-c 03:00:00:00:ff:00
```
The -n suppressed the automatic REQUEST SENSE.

**Comment by Pacjunk** [comment]
[test_writable2.txt](https://github.com/user-attachments/files/17992184/test_writable2.txt)

**Comment by uweseimet** [comment]
Now it's fine. Again with some custom bytes at the end:
```
00000000  f0:00:20:00:00:00:1c:12:00:00:00:00:00:00:00:00  '.. .............'
00000010  ca:00:00:00:00:00:00:1d:1e:3a                    '.........:'
```
I have to figure out what to do next. If this is the only difference between what your drive does with this script and what s2p does, I will temporarily tweak s2p to return excactly the same data, assuming that your driver will proceed then, becasue it receives the same data as will your real drive.

**Comment by Pacjunk** [comment]
I know I have asked this before, but is it possible to have a program that just records the traffic between the initiator and a nominated SCSI ID?  That way you could get a snapshot of the two way conversation involved with a real drive and see if s2p does similar?

**Comment by uweseimet** [comment]
As already mentioned, in theory the scsimon tool (PiSCSI) might do that. In practice I doubt that it works, because your computer and drive will likely communicate faster than the Pi can record the data. Or they might even use synchronous transfers, which the Pi would not be able to log at all. But you can give it a try. You will probably get a very verbose log with some (but not all) of the data on the bus.

But all commands and data sent are logged in the s2p and s2pexec logs. There is nothing else, i.e. recording the traffic would not reveal more information.

**Comment by Pacjunk** [comment]
Just ran it. Don't know what the data means. I think one file is signal waveforms, and html file looks more readable but is severely lacking detail.

**Comment by uweseimet** [comment]
I compared the two logs: Except for the additional sense data returned by your drive when 90 instead of the available bytes are read the command execution is identical. This means that either the additional data are relevant, or it is something else that happened before, which I have missed. But there is not that much happening in the foreign test, and it stops right after the different error data were returned.
The latest issue_100 sources contain a tweak so that s2p returns exactly the same data as your drive:
```
00000000  f0:00:20:00:00:00:1c:12:00:00:00:00:00:00:00:00  '.. .............'
00000010  ca:00:00:00:00:00:00:1d:1e:3a                    '.........:'
```

**Comment by Pacjunk** [comment]
Build 18a0306

Still a problem:
[foreignlist.txt](https://github.com/user-attachments/files/18001433/foreignlist.txt)
[foreignlist script.txt](https://github.com/user-attachments/files/18001434/foreignlist.script.txt)

I'm beginning to wonder if this is a tape position issue. When the tape is mounted foreign, subsequent commands don't rewind the tape, but just continue on from the last position. The mount itself does a rewind, and if I force a rewind manually the results are the same. The command to list the tapes' content complains that it has an invalid label, so maybe the "resting place" after a rewind is not correct?

Mounting the tape "non-foreign" works fine, but its probably doing everything in one operation. ie rewinding, then loading data, whereas with foreign, the rewind and the read are part of different commands.

**Comment by uweseimet** [comment]
The tape position is a good point, indeed. I am not sure what this means for testing, though. Which sequence of scripts or command would be the required one? When you use your real tape, what is the matching sequence of scripts/commands? What I mean is, when you run the foreign mount operation with your drive, which operations were run before? We already have scripts for everything, don't we?

**Comment by uweseimet** [comment]
@Pacjunk This ticket is dealing with SIMH file support, but this has already been implemented and we are now dealing with other issues. In addition, I am losing track of all the scripts, logs etc. attached to this ticket.
I would like to close this ticket and create a more specific one on the problems we are facing. Can you please provide the name of your workstation and driver etc. so that I can set up a more specific ticket. You may have provided this information in the past, but it has become hard to find information in this ticket.

**Comment by Pacjunk** [comment]
According to the trace log the last thing the mount/foreign command does is a rewind, so it should be ready for the next command (that we have been analysing). The message the OS gives when trying to list the contents is "tape is not valid ANSI format" - so its obviously trying to look for the ansi field markers e.g. VOL1, HDR1 etc

Is there a way to get the trace dump to display the contents of the data read? ie the 80 or 90 bytes. Then we could see if the data aligns with those field markers.

I'm testing on a VAXstation 3100 running OpenVMS 7.2.

**Comment by uweseimet** [comment]
The trace dumps already display the contents, as long as there is no mismatch between the byte count. Otherwise they cannot display any content because the READ command terminates with an error message.
If you have read 80 bytes and the block size matches these 80 bytes you get this dump on trace level:
```
00000000  56:4f:4c:31:54:45:53:54:33:33:20:20:20:20:20:20  'VOL1TEST33      '
00000010  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000020  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000030  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000040  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:33  '               3'
```
You get the same output when running s2psimh on the same image file:
```
>s2psimh -d ~/hatari/test.tap
Offset 0 ($0): Class 0, good data record, record length 80 ($50)
00000000  56:4f:4c:31:54:45:53:54:33:33:20:20:20:20:20:20  'VOL1TEST33      '
00000010  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000020  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000030  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  '                '
00000040  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:33  '               3'
```
Everything is IMO consistent here, i.e. for a given position on the tape s2p reads and displays the same data as s2psimh.

**Comment by uweseimet** [comment]
@Pacjunk I created https://github.com/uweseimet/scsi2pi/issues/111 in order to deal with testing with your hardware.

**Comment by uweseimet** [comment]
@pacjunk There is a new issue_111 branch now, which replaces the issue_100 branch for testing. Please run "git pull" and then "git checkout issue_111". Currently, issue_111 is identical with issue_100. Any further commits will go to issue_111.
